name: franq
description: A pokemon Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


scripts:
  runner: flutter pub run build_runner watch --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^6.0.0-alpha.5
  http: ^0.13.5
  bloc: ^8.1.1
  image_picker: ^0.8.6
  flutter_bloc: ^8.1.2
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  cloud_firestore: ^4.4.2
  firebase_storage: ^11.0.13
  firebase_analytics: ^10.1.3
  firebase_crashlytics: ^3.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.1
  mockito: ^5.3.2
  build_runner: ^2.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/pokemon-png-logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

